#!/bin/bash
# Fix 502 Bad Gateway - Check security groups and provide instructions

EC2_USER="ec2-user"
EC2_HOST="13.62.127.241"
KEY_PATH="/home/fashionx/xapien.pem"

echo "🔍 Diagnosing 502 Bad Gateway issue..."
echo ""
echo "Nginx is running and listening on port 7077 ✅"
echo ""
echo "Common causes of 502 Bad Gateway with AWS Load Balancer:"
echo ""
echo "1. ⚠️  SECURITY GROUP - Port 7077 must be open:"
echo "   - Go to EC2 Console → Security Groups"
echo "   - Find your EC2 instance's security group"
echo "   - Add Inbound Rule:"
echo "     Type: Custom TCP"
echo "     Port: 7077"
echo "     Source: Your Load Balancer Security Group (or 0.0.0.0/0 for testing)"
echo ""
echo "2. ⚠️  LOAD BALANCER TARGET GROUP:"
echo "   - Check Target Group → Health Checks"
echo "   - Health check path should be: /"
echo "   - Health check port should be: 7077"
echo "   - Protocol: HTTP"
echo "   - Make sure targets are 'healthy'"
echo ""
echo "3. ⚠️  LOAD BALANCER LISTENER:"
echo "   - HTTPS (443) → Forward to Target Group on port 7077"
echo "   - Or HTTP (80) → Forward to Target Group on port 7077"
echo ""
echo "4. Testing from outside..."
ssh -i $KEY_PATH $EC2_USER@$EC2_HOST "curl -I http://localhost:7077 2>&1 | head -5"

echo ""
echo "📋 Quick AWS CLI commands to check (if you have AWS CLI installed):"
echo ""
echo "# Check security groups:"
echo "aws ec2 describe-instances --instance-ids <YOUR_INSTANCE_ID> --query 'Reservations[0].Instances[0].SecurityGroups'"
echo ""
echo "# Check target group health:"
echo "aws elbv2 describe-target-health --target-group-arn <YOUR_TARGET_GROUP_ARN>"
echo ""

